---
abstract: unknown
author:
  - unknown
build_requires:
  JSON: 2.53
  TestML: 0.27
  YAML: 0.84
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: JSONY
no_index:
  directory:
    - t
    - inc
requires:
  Pegex: 0.20
  boolean: 0.28
version: v0.0.6
