---
abstract: 'Relaxed JSON with a little bit of YAML'
author:
  - 'Ingy döt Net <ingy@cpan.org>'
build_requires:
  JSON: '2.90'
  YAML: '0.90'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.012, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: JSONY
requires:
  Pegex: '0.30'
  boolean: '0.31'
  perl: v5.8.1
resources:
  bugtracker: https://github.com/ingydotnet/jsony-pm/issues
  homepage: https://github.com/ingydotnet/jsony-pm
  repository: https://github.com/ingydotnet/jsony-pm.git
version: 0.1.0
